name: radial-web-app
channels:
  - Microsoft
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - click=8.0.3=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.4.1=py37h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - flask=2.0.2=pyhd3eb1b0_0
  - icu=69.1=h9c3ff4c_0
  - importlib-metadata=4.8.1=py37h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.2.0=py37h06a4308_1
  - ipython=7.27.0=py37hb070fc8_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jansson=2.14=h7f98852_0
  - jedi=0.18.0=py37h06a4308_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - openssl=1.1.1l=h7f8727e_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py37h06a4308_0
  - prompt-toolkit=3.0.17=pyhca03da5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pyzmq=22.2.1=py37h295c915_1
  - readline=8.1=h27cfd23_0
  - ruamel.yaml=0.16.12=py37h7b6447c_1
  - ruamel.yaml.clib=0.2.2=py37h7b6447c_0
  - scipy=1.7.1=py37h292c36d_2
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - uwsgi=2.0.20=py37hc1dc9ca_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
    - anyio==3.3.2
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - babel==2.9.1
    - bleach==4.1.0
    - cachelib==0.4.1
    - cffi==1.14.6
    - charset-normalizer==2.0.6
    - cycler==0.10.0
    - defusedxml==0.7.1
    - flask-session==0.4.0
    - idna==3.2
    - ipython-genutils==0.2.0
    - jinja2==3.0.1
    - json5==0.9.6
    - jsonschema==4.0.1
    - jupyter-server==1.11.0
    - jupyterlab==3.1.14
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - mistune==0.8.4
    - nbclassic==0.3.2
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - notebook==6.4.4
    - numpy==1.21.2
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.5.0
    - pillow==8.3.2
    - prometheus-client==0.11.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytz==2021.3
    - requests==2.26.0
    - requests-unixsocket==0.2.0
    - scikit-learn==1.0
    - send2trash==1.8.0
    - sniffio==1.2.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - urllib3==1.26.7
    - webencodings==0.5.1
    - websocket-client==1.2.1
prefix: /home/ryanpapetti/anaconda3/envs/capstone
